spring:
  application:
    name: Ludotheque

  datasource:
    url: jdbc:sqlserver://localhost;databasename=LUDO_DB;encrypt=false
    username: LUDO_USER
    password: "LUDO_PWD"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

